// lib/bingo.ts
// Default pool items (single source of truth).
// These are used by BOTH generator + caller as "defaults".

export const BINGO_ITEMS: string[] = [
  "Joe’s Grows",
  "Harvest Heroes",
  "Cal-Mag",
  "pH Down",
  "pH Up",
  "EC Check",
  "PPM Check",
  "VPD Check",
  "Leaf Temp Check",
  "Canopy Temp Check",
  "Humidity Spike",
  "Heat Stress",
  "Cold Snap",
  "Lights On",
  "Lights Off",
  "Timer Issue",
  "Power Outage",
  "Light Burn",
  "Nute Burn",
  "Lockout",
  "pH Swing",
  "Overwatered",
  "Underwatered",
  "Dry Back",
  "Runoff EC",
  "Reservoir Change",
  "Top Off",
  "AirStone",
  "Pump Check",
  "Clogged Line",
  "Leaky Fitting",
  "Root Check",
  "Root Rot Watch",
  "Slimy Roots",
  "Bennies Added",
  "Hydrogen Peroxide",
  "Silica Added",
  "PK Boost",
  "Defoliation",
  "Lollipop",
  "Trellis Net",
  "Support Stakes",
  "Training Day",
  "Supercrop",
  "FIM",
  "Topping",
  "Tie-Downs",
  "Stem Rub",
  "Stretch Week",
  "Pre-Flower",
  "Bud Sites Stacking",
  "Foxtails",
  "Trichomes",
  "Cloudy Trichomes",
  "Amber Check",
  "Funky Terps",
  "Sweet Terps",
  "Gas Terps",
  "Purple Fade",
  "Late Flower Fade",
  "Sugar Leaves",
  "Fan Leaves",
  "Leaf Taco",
  "Clawing Leaves",
  "Spots on Leaves",
  "Yellowing Leaves",
  "Calcium Deficiency",
  "Magnesium Deficiency",
  "Nitrogen Deficiency",
  "Potassium Deficiency",
  "Micros Deficiency",
  "IPM Spray",
  "Sticky Traps",
  "Fungus Gnats",
  "Spider Mites",
  "Thrips",
  "Aphids",
  "Powdery Mildew",
  "Bud Rot Watch",
  "Neem Smell",
  "Sticky Scissors",
  "Trim Jail",
  "Harvest Day",
  "Wet Trim",
  "Dry Trim",
  "Hang Dry",
  "Dry Room Check",
  "Jar Time",
  "Burp Jars",
  "Cure Check",
  "Smoke Test",
  "Growmie Advice",
  "New Genetics",
  "Seed Pop",
  "Clone Day",
  "Transplant",
  "Pray for Yield",
  "Send Pics",
  "Winner Winner",
];
