// lib/bingo.ts

export const BINGO_ITEMS: string[] = [
  "Joe’s Grows",
  "Harvest Heroes",
  "Cal-Mag",
  "pH Down",
  "pH Up",
  "EC Check",
  "PPM Check",
  "VPD Check",
  "Leaf Temp Check",
  "Canopy Temp Check",
  "Humidity Spike",
  "Heat Stress",
  "Cold Snap",
  "Lights On",
  "Lights Off",
  "Power Outage",
  "Timer Check",
  "Reservoir Change",
  "Top Off",
  "AirStone",
  "Pump Failure",
  "Root Check",
  "Slimy Roots",
  "Defoliation",
  "Lollipop",
  "Stretch Week",
  "Pre-Flower",
  "Trichomes",
  "Amber Check",
  "Flush Time",
  "Dry Back",
  "Runoff Check",
  "Nute Burn",
  "Lockout",
  "Funky Terps",
  "Frosty Buds",
  "Bud Rot Watch",
  "IPM Spray",
  "Sticky Scissors",
  "Trellis Net",
  "Support Stakes",
  "Clone Day",
  "Transplant",
  "Training Day",
  "Topping",
  "FIM",
  "Supercrop",
  "Fan Leaves",
  "Sugar Leaves",
  "Trim Jail",
  "Jar Time",
  "Cure Check",
  "Burp Jars",
  "Humidity Control",
  "Dehumidifier On",
  "Humidifier On",
  "CO₂ Debate",
  "Environment Dialed",
  "Light Stress",
  "Foxtails",
  "Seed Pop",
  "New Genetics",
  "Pheno Hunt",
  "Smoke Test",
  "Growmie Advice",
  "Send Pics",
  "Pray for Yield",
  "Winner Winner",
];
